# Generated by Django 2.2.1 on 2019-05-09 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('postalcode', models.CharField(max_length=12)),
                ('location', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('bedrooms', models.IntegerField(max_length=2)),
                ('size', models.IntegerField(max_length=4)),
                ('price', models.IntegerField(max_length=9)),
                ('agentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.Agent')),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=999)),
                ('mainimage', models.BooleanField()),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.Apartment')),
            ],
        ),
    ]
