# Generated by Django 2.2.1 on 2019-05-09 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='name',
        ),
    ]
