# Generated by Django 2.2.1 on 2019-05-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='description',
            field=models.CharField(default='description', max_length=255),
        ),
    ]
