# Generated by Django 2.2.1 on 2019-05-16 13:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apartments', '0003_apartmentorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentorder',
            name='user',
        ),
        migrations.AddField(
            model_name='apartmentorder',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
