# Generated by Django 2.2.1 on 2019-05-16 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apartments', '0006_auto_20190516_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentorder',
            name='user',
        ),
        migrations.AddField(
            model_name='apartmentorder',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
