# Generated by Django 2.2.1 on 2019-05-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0007_auto_20190516_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentorder',
            name='user',
            field=models.IntegerField(max_length=255),
        ),
    ]
