# Generated by Django 2.2.1 on 2019-05-16 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0008_auto_20190516_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
