# Generated by Django 2.2.1 on 2019-05-09 10:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=255)),
                ('admin', models.BooleanField(default=False)),
                ('startdate', models.DateField()),
                ('profilepicture', models.CharField(blank=True, max_length=255)),
                ('cellphone', models.CharField(max_length=15)),
                ('workphone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=255)),
                ('license', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('rating', models.IntegerField(max_length=1)),
                ('comments', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=140), size=None)),
            ],
        ),
    ]
