# Generated by Django 2.2.1 on 2019-05-09 15:36

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('socialsecurity', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=255)),
                ('startdate', models.DateField()),
                ('profilepicture', models.CharField(blank=True, max_length=255)),
                ('cellphone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=255)),
                ('searchhistory', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=140), size=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
