# Generated by Django 2.2.1 on 2019-05-17 13:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='searchhistory',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=140, null=True), size=None),
        ),
    ]
