# Generated by Django 2.2.1 on 2019-05-17 13:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190517_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='searchhistory',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=list, max_length=140), size=None),
        ),
    ]
